version: '3.4'

services:
  api:
    image: feed/gateway
    container_name: feed.gateway
    hostname: gateway
    ports:
    - "8080:8080"
    restart: always
    links:
    - rabbit
    - user_service
    build:
      context: ./gateway
      dockerfile: Dockerfile
    command: uvicorn main:app --reload --port 8080 --host 0.0.0.0
    networks:
      - app-network
  user_service:
    container_name: feed.services.users
    image: feed/users
    restart: always
    build:
      context: ./services/users
      dockerfile: Dockerfile
    command: /bin/bash run.sh

    networks:
      - app-network
  feed_service:
    container_name: feed.services.feeds
    image: feed/feeds
    restart: always
    build:
      context: ./services/feeds
      dockerfile: Dockerfile
    command: /bin/bash run.sh

    networks:
      - app-network

  rabbit:
    container_name: nameko.rabbit
    image: rabbitmq:3-management
    restart: always
    ports:
      - "15672:15672"
      - "5672:5672"
    environment:
      RABBITMQ_ERLANG_COOKIE:
      RABBITMQ_DEFAULT_VHOST: /
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS}
    networks:
      - app-network

  celery:
    container_name: nameko.celery
    restart: always
    build:
      context: ./services/feeds
      dockerfile: Dockerfile
    command: celery -A celery_worker  worker -B
    depends_on:
      - rabbit
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
