AMQP_URI: 'pyamqp://guest:guest@rabbit'
WEB_SERVER_ADDRESS: '0.0.0.0:8001'
rpc_exchange: 'nameko-rpc'
max_workers: 10
parent_calls_tracked: 10
DB_URIS:
  'feed_service:Base': 'sqlite:///feed_database.db'

LOGGING:
  version: 1
  handlers:
    console:
      class: logging.StreamHandler
  root:
    level: DEBUG
    handlers: [console]